"""
Python -arrays...
aarays are used to store information in a single values...
"""

name = ['DAVID', 'BRIAN','SUNSHAYINA']

#Array can hold more values at a time....
print name #this is to print array of names....
