#here, we are going to learn how to make a python functions...
def python_function(): #this is python declaration...
  print("Hello friends, am learning python Functions")

python_function() #this is python call...